import React from 'react'
import { Row, Col } from 'reactstrap'
import './index.scss'

const WritingCenter = () =>
  <Row className='scholarship mt-4 page-wrapper' tag={'main'}>
    <Col xs={12} xl={6}>
      <h1>{'Scholarship'}</h1>
      <p>
        {'My research agenda focuses on questions related to disability and collaboration, with the goal of creating and maintaining accessible environments for disabled students and academics. While much of the accessibility research in composition emphasizes physical disabilities such as sight, hearing, or mobility, my work examines ways in which writing studies has ignored the experiences of neurodivergent (e.g., anxiety, depression, autism, ADHD, and other related disabilities) individuals. My work is greatly informed by both Jay Dolmage’s and Margaret Price’s scholarship, in which we consider how academic systems can exclude and marginalize disabled individuals. My scholarship is informed by my own experiences as a disabled academic and my desire to advocate for accessibility in higher education. This interest has informed my dissertation project and lines of inquiry that I will continue to explore in the future.'}
      </p>
      <p>
        {'My dissertation, Including Disability in Collaborative Writing Pedagogy, features disabled students’ voices as they describe their experiences with collaborative learning and writing in the classroom and reimagine a structure that is more accessible to their abilities. In order to better understand these students’ experiences, I conducted interviews and surveys while using Margaret Price and Stephanie Kerschbaum’s (2016) Interdependent Disability Studies Methodology to guide my data collection and analysis. My results have yielded important insights that will serve as the foundation for several projects. To begin with, I am currently working on an article that will explore how to build what Elizabeth Brewer and colleagues (2014) call a “culture of access” in first-year composition courses with the inclusion of collaborative assignments. Additionally, this research will also be used to inform my upcoming co-authored chapter in the fifth edition of Writing Spaces. This chapter will explore techniques and technologies students can use to collaborate effectively with one another.'}
      </p>
      <p>
        {'My immediate plan is to expand the scope of this research into a cross-institutional study that will lead to several outcomes, both shorter and longer publications. A cross-institutional study would allow me to achieve three things that were outside the scope of my dissertation. First, it would allow me to better understand how issues of race, gender, and type of disability impact neurodivergent students’ experiences with collaboration. My study was focused on individuals within one program, which provided deep insight into specific students’ experiences, but the sample size lacked some key demographics. By broadening the population, the study’s claims can become more generalizable to programs outside one particular institution. Second, it would allow me to examine more closely how instructors teach collaboration. My project explored students’ perceptions and experiences with classroom collaborative writing, which left me questioning how instructors incorporated collaboration and how they perceived the support they offered. A clearer understanding of how instructors incorporate and support collaboration in their classrooms can lead to targeted interventions to improve collaborative assignments. Third, it would enable an exploration of how neurodivergent students conceptualize their disability identity and whether or not they register for disability services. The results of my research showed that while neurodivergent students fall under the category of disabled, many of them do not identify with that label. Collecting information on this topic will help us better understand the identity formation of neurodivergent students and determine what kind of support they need. These studies combined can give us a broader view of how students navigate the university with disabilities and how instructors can better support their disabled students.'}
      </p>
      <p>
        {'I am also invested in exploring topics related to increasing the accessibility of environments outside of the classroom. For example, I was invited to contribute to a recent College Composition and Communication’s symposium on conference accessibility. In this piece, my coauthor and I advocated for the inclusion and respect of quiet rooms (i.e., rooms set aside with the intended purpose to provide safe spaces for individuals who experience sensory overload) in conferences. In conjunction with the other essays, we argued for the value of conference accessibility and articulated the work that still needs to be done by conference organizers. In addition to that piece, I also have an article that I am in the process of revising for resubmission to College Composition and Communication which delves deeper into graduate students’ positionality and conference accessibility. For future projects, I envision that I will continue exploring ways that we can make the field of writing studies more accessible by expanding my research to consider other writing study spaces such as writing centers and graduate programs.'}
      </p>
    </Col>
    <Col xs={12} xl={6} className='text-center'>
      <img className='mb-4 mr-4' title='4 Happy Scholars' alt='Ellen sits to the left of two other scholars behind a table, smiling at the camera. Another scholar is projected up on screen in a video call.' src={require('../../../images/4sittingscholars.png')} />
      <img title='4 Happy Scholars Plus Rosie' alt='Ellen stands to the right of 3 other scholars, posing for a picture. Rosie sits at her feet looking away from the camera.' src={require('../../../images/4standingscholars.png')} />
    </Col>
  </Row>

export default WritingCenter
